---
packages:
- name: common
  version: 0.1-dev
  sha1: !binary |-
    ZDJkMzM5YWYxODE5ZGIzMWY1ODZjY2RiYzA3OGYyNmFiMGVmMGI3NQ==
  fingerprint: !binary |-
    NDNkMzdhMTUzOGFkNWY0Zjk4YTA3Mzk2ODk0ODI0MzJiZjg2MzBjNA==
  dependencies: []
- name: gemfire_jvm7
  version: 0.1-dev
  sha1: !binary |-
    ODU0MTBhMmQxODQ1YmYwNmYwYzM1ZWIyYjlmNThiNDgwZmExNDJkOA==
  fingerprint: !binary |-
    ZTgyZTRkMDY0ZWNlODA3NGZkZmUxZDdlYTBjYjY1NTg2YzNlM2QzNQ==
  dependencies: []
- name: gemfireserver
  version: 0.1-dev
  sha1: !binary |-
    NGM5YTRmNzBkODFhYTA1MDQwZjFmZDBlMDZiMjE5NmQ3NDQxYzJiNg==
  fingerprint: !binary |-
    NzcyZDEwZWQ0ZDBhN2E4NjQ2MWMyOTFiNDBhYmZlNmE2YjQ4ZmNmMQ==
  dependencies:
  - gemfire_jvm7
jobs:
- name: gemfirelocator
  version: 0.1-dev
  fingerprint: !binary |-
    ZGY1ZTBlNjYxN2FmOGJmNzQ4ZDJiZTE1YmQ1MTYwNDNjYjk1Y2NjMw==
  sha1: !binary |-
    ZTY0OWUyN2Q5ZjczZGYzMmI3NzNlOTAwMDYwOTg2MDhjMGE3NWNiNA==
- name: gemfireserver
  version: 0.1-dev
  fingerprint: !binary |-
    MThiOTU3MWY2Nzg1MTA2N2VkNTRlZTRjMmM3MWZjZTU0MzczZTc1Zg==
  sha1: !binary |-
    NTA4ZmNjZGZhZWRkNzZiMDBiYTExNDk1MTYyMzQ1MGIwOTUxZGIwNQ==
commit_hash: 3c461d9c
uncommitted_changes: false
name: cf-gemfire
version: 0.1-dev
