#!/bin/bash -e

BIN_DIR=/var/vcap/packages/gemfireserver/gemfire-service-broker
RUN_DIR=/var/vcap/sys/run/gemfireserver
LOG_DIR=/var/vcap/sys/log/gemfireserver
JOB_DIR=JOB_DIR=/var/vcap/jobs/gemfireserver
PIDFILE=$RUN_DIR/gemfireserver.pid
STDOUTLOG=$LOG_DIR/gemfireserver.stdout.log
STDERRLOG=$LOG_DIR/gemfireserver.stderr.log

export JAVA_HOME=/var/vcap/packages/gemfire_jvm7
export PATH=$PATH:$JAVA_HOME/bin:$BIN_DIR

HEAP=<%= properties.gemfire_server.memory.to_s + "m" %>

source /var/vcap/packages/common/utils.sh

case $1 in

  start)
    pid_guard $PIDFILE "gemfire"

    mkdir -p $RUN_DIR
    mkdir -p $LOG_DIR
    cd $BIN_DIR

    PROP_DIR=`dirname "$0"`
	echo "Current Dir for props: $PROP_DIR"

	java -Xms$HEAP -Xmx$HEAP -Dprops-file=$PROP_DIR/gemfire.properties -Dspring.profiles.active=gemfire-server -Djava.net.preferIPv4Stack=true -cp cf-brokers-0.0.1-SNAPSHOT.jar com.pivotal.cloudfoundry.service.broker.gemfire.GemfireServer > $STDOUTLOG &
	sleep 10
	ps aux | grep GemfireServer | grep -v grep | awk '{print $2}' > $PIDFILE
    while read line           
	do           
    	echo "Gemfire PID: $line"     
	done <$PIDFILE 
    
    ;;

  stop)
    kill_and_wait $PIDFILE

    ;;

  *)
    echo "Usage: gemfireserver_ctl {start|stop}"

    ;;

esac
